trigger:
 branches:
   include:
     - release*

pr:
  branches:
    include:
     - main
  paths:
    exclude:
    - README.md

resources:
  repositories:
    # - repository: MlApp
    #   type: githubenterprise
    #   name: gsk-tech/si-template
    #   endpoint: GSK GitHub xox87765 OAuth
    #   ref: main
    - repository: MlOps
      type: github
      name: sugamg/powershell
      endpoint: MyGit
      ref: $(Build.SourceBranch)

steps:
- checkout: MlOps
- script: echo $(Build.SourceBranch)



#stages:          
# Call the stages in the MlOps repo
#    - template: databricks-ml/pipelines/stages/mlops-main-stage.yml@MlOps  # Template reference 
