trigger:
 branches:
   include:
     - release*

pr:
  branches:
    include:
     - main
  paths:
    exclude:
    - README.md

resources:
  repositories:
    - repository: MlApp
      type: github
      name: sugamg/pipeline-docker
      endpoint: MyGit
      ref: main
    - repository: MlOps
      type: github
      name: sugamg/powershell
      endpoint: MyGit
      ref: $(Build.SourceBranch)

steps:
- checkout: MlOps
- script: echo $(Build.SourceBranch)



#- template: mlops-main-stage.yml@MlOps  # Template reference 
