trigger:
 branches:
   include:
     - release*

pr:
  branches:
    include:
     - main
  paths:
    exclude:
    - README.md

resources:
  repositories:
    - repository: MlApp
      type: github
      name: sugamg/pipeline-docker
      endpoint: MyGit
      ref: master
    - repository: MlOps
      type: github
      name: sugamg/powershell
      endpoint: MyGit
      ref: $(Build.SourceBranch)


- template: mlops-main-stage.yml@MlApp  # Template reference 
